name: CI for the CAF-RNTuple Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rootproject/root
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Clone external package (duneanaobj) and CAFTEST
        run: |
          mkdir /workarea && cd /workarea
          git clone --recurse-submodules https://github.com/hep-cce2/CAF-RNTuple.git
          cd /workarea/CAF-RNTuple
          mkdir /workarea/CAF-RNTuple/build && cd /workarea/CAF-RNTuple/build
          cmake -DCMAKE_MODULE_PATH=/opt/root/cmake /workarea/CAF-RNTuple
          make


 #     - name: Run tests
 #       run: |
 #         cd CAF-RNTuple/build
 #         Unitary test codes here

